# Configuration de Thymeleaf (Question 1)
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false

# Configuration des ressources statiques (Question 2)
spring.web.resources.static-locations=classpath:/static/
